# Generated by Django 2.1.2 on 2018-10-13 18:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptcs', djongo.models.fields.DictField()),
                ('ssdkl', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure', models.DateField()),
                ('campaign', models.CharField(default='base', max_length=20)),
            ],
        ),
    ]
